version: '3'

services:
  mysqldb:
    image: mysql:8.0.1
    restart: always
    env_file: .env 
    environment: 
      - MYSQL_USER=$DATABASE_USER
      - MYSQL_ROOT_PASSWORD=$DATABASE_PASSWORD
      - MYSQL_DATABASE=$DATABASE_NAME
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    expose:
      - $MYSQL_LOCAL_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: .
    restart: unless-stopped
    env_file: .env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$DATABASE_USER
      - DB_PASSWORD=$DATABASE_PASSWORD
      - DB_NAME=$DATABASE_NAME
      - DB_PORT=$MYSQL_LOCAL_PORT
    stdin_open: true
    tty: true
    expose:
      - $NODE_LOCAL_PORT
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on: 
      - mysqldb
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysqldb
      - PMA_PORT=$MYSQL_LOCAL_PORT
volumes:
  db: